### PR TITLE
foo

### PR DESCRIPTION
**Pull request by jsquyres**
Signed-off-by: Jeff Squyres <jsquyres@cisco.com>

### CODE REVIEW

**Comment by captivita** [comment]
sadness

**Comment by captivita** [comment]
No test results found.

**Comment by captivita** [comment]
No test results found.

**Comment by captivita** [comment]
No test results found.

**Comment by captivita** [comment]
No test results found.

**Comment by captivita** [comment]
No test results found.

**Comment by captivita** [comment]
sobriety
saintly

**Comment by captivita** [comment]
chicken soup

**Comment by jsquyres** [comment]
chicken soup

**Comment by captivita** [comment]
resubmit PR

**Comment by captivita** [comment]
resubmit PR

**Comment by captivita** [comment]
Can't set status; build failed.

**Comment by captivita** [comment]
Can't set status; build failed.

**Comment by captivita** [comment]
cisco-usnic-bot:retest

**Comment by jsquyres** [comment]
retest

**Comment by captivita** [comment]
cisco-usnic-bot:retest

**Comment by captivita** [comment]
cisco-usnic-bot:retest

**Comment by jsquyres** [comment]
cisco-usnic-bot:retest

**Comment by jsquyres** [comment]
@captivita I notice that builds 26 and 27 on the internal jenkins thing that these builds failed.  Here's a snipit from their console output:

```
++ tee -i output.txt
+ touch /scratch/tools/Jenkins/workspace/cspg_github_jsquyres_libfabric/.in-progress.txt
+ ssh ucsbld@savbu-releng-lab8 /build/tools/github.build
Already up-to-date.
+ ssh usnic@vic-automation ./testrun.sh
#-#-# PASS #-#-#
+ rm /scratch/tools/Jenkins/workspace/cspg_github_jsquyres_libfabric/.in-progress.txt
ERROR: Build step failed with exception
java.lang.NullPointerException
	at org.jenkinsci.plugins.github.pullrequest.publishers.impl.GitHubPRBuildStatusPublisher.perform(GitHubPRBuildStatusPublisher.java:92)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:401)
```

There doesn't seem to be an obvious reason as to why the exception is occurring -- do you think it's the item you cited in email:

```
Setting commit status on GitHub for https://github.com/jsquyres/libfabric/commit/89cff60fdcd729bb08dce8e4b69cf021d87f6284
ERROR: [GitHub Commit Status Setter] Failed to update commit state on GitHub. Ignoring exception [{"message":"Not Found","documentation_url":"https://developer.github.com/v3"}]
```

In the console output for builds 26 and 27 (https://savbu-ucs-bld61.cisco.com/jenkins/job/cspg_github_jsquyres_libfabric/26/console and https://savbu-ucs-bld61.cisco.com/jenkins/job/cspg_github_jsquyres_libfabric/27/console), I see that error up near the top of the job -- not anywhere close to where this java language exception is occurring.

I'm guessing that this "Status setter" failure is failing to set the status to be "building" on github.com.  The status is successfully set to "failed" later in the job, however (i.e., the CI entry has a red "X" here on github.com).  So it's odd that it seems like setting the status works *sometimes*, but *sometimes* it doesn't.  😦

**Pull request closed without merging**
