### PR TITLE
Jenkins testing

### PR DESCRIPTION
**Pull request by jsquyres**
CJ: here's a PR where we can do some testing for the Cisco Jenkins server to publicly test / post gists back to github.com.

### CODE REVIEW

**Comment by jsquyres** [comment]
@captivita Here's a PR to play with on github.com.

**Comment by captivita** [comment]
sadness

**Comment by captivita** [comment]
No test results found.

**Comment by captivita** [comment]
Can't set status; build failed.

**Comment by captivita** [comment]
Can't set status; build failed.

**Pull request closed without merging**
